### ISSUE TITLE
nokogiri-1.8.2/lib/nokogiri/xml/node.rb:814:in `coerce': Requires a Node, NodeSet or String argument, and cannot accept a NilClass. (ArgumentError)

### ISSUE THREAD

**Issue by cavalryjim** [softcover/softcover#198]
I've successfully installed Softcover on my Raspberry Pi B+ but I receive an nokogiri error when trying to run the Softcover server.  Output is below.
```
$ ruby -e 'puts RUBY_PLATFORM'
armv7l-linux-eabihf

james@raspberrypi:~/Projects/entr4701_book $ sc check
Checking Softcover dependencies...
Checking for LaTeX...         Found
Checking for GhostScript...   Found
Checking for ImageMagick...   Found
Checking for Node.js...       Found
Checking for PhantomJS...     Found
Checking for Inkscape...      Found
Checking for Calibre...       Found
Checking for KindleGen...     Found
Checking for Java...          Found
Checking for zip...           Found
Checking for EpubCheck...     Found
All dependencies satisfied.
james@raspberrypi:~/Projects/entr4701_book $ sc s
Building.../home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node.rb:814:in `coerce': Requires a Node, NodeSet or String argument, and cannot accept a NilClass. (ArgumentError)
(You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node.rb:246:in `children='
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node.rb:234:in `inner_html='
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/polytexnic-1.4.0/lib/polytexnic/utils.rb:170:in `block in highlight_source_code'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:190:in `block in each'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `upto'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `each'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/polytexnic-1.4.0/lib/polytexnic/utils.rb:166:in `highlight_source_code'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/polytexnic-1.4.0/lib/polytexnic/postprocessors/html.rb:1295:in `convert_to_html'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/polytexnic-1.4.0/lib/polytexnic/postprocessors/html.rb:61:in `xml_to_html'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/polytexnic-1.4.0/lib/polytexnic/postprocessor.rb:16:in `postprocess'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/polytexnic-1.4.0/lib/polytexnic.rb:91:in `to_html'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/builders/html.rb:123:in `converted_html'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/builders/html.rb:43:in `build'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/commands/server.rb:47:in `rebuild'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/commands/server.rb:63:in `run'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/cli.rb:107:in `server'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/gems/softcover-1.5.1/bin/sc:4:in `<top (required)>'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/bin/sc:23:in `load'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/bin/sc:23:in `<main>'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/bin/ruby_executable_hooks:15:in `eval'
	from /home/james/.rvm/gems/ruby-2.4.1-use-rvm@softcover/bin/ruby_executable_hooks:15:in `<main>'
james@raspberrypi:~/Projects/entr4701_book $ 
```

**Comment by mhartl** [comment]
Thanks for the heads-up. It looks like we may need to add an additional [tralics](https://github.com/softcover/tralics) binary to the [polytexnic](https://github.com/softcover/polytexnic
) gem. 

If you'd like to help do this, please follow the instructions in the [tralics README](https://github.com/softcover/tralics#tralics) to compile a binary for your system, and then send it to the email address listed. Thanks!

**Comment by mhartl** [comment]
Oops, just noticed you already sent one. I'll incorporate it ASAP.

**Comment by mhartl** [comment]
OK, I've released a new gem. You can update it as follows:
```
gem update polytexnic
```
The new version number should be `1.4.1`. Let me know if it works!

**Comment by cavalryjim** [comment]
Unfortunately, that did not fix the problem.  Looking at the documentation, I downgraded to an earlier version of Ruby.  Here is the output from using Ruby 2.2.2.

```
james@raspberrypi:~/Projects/entr4701_book $ gem list softcover

*** LOCAL GEMS ***

softcover (1.5.1)
james@raspberrypi:~/Projects/entr4701_book $ gem list polytexnic

*** LOCAL GEMS ***

polytexnic (1.4.1)
james@raspberrypi:~/Projects/entr4701_book $ gem list nokogiri

*** LOCAL GEMS ***

nokogiri (1.8.2)
james@raspberrypi:~/Projects/entr4701_book $ softcover check
Checking Softcover dependencies...
Checking for LaTeX...         Found
Checking for GhostScript...   Found
Checking for ImageMagick...   Found
Checking for Node.js...       Found
Checking for PhantomJS...     Found
Checking for Inkscape...      Found
Checking for Calibre...       Found
Checking for KindleGen...     Found
Checking for Java...          Found
Checking for zip...           Found
Checking for EpubCheck...     Found
All dependencies satisfied.
james@raspberrypi:~/Projects/entr4701_book $ sc s
Building.../home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node.rb:814:in `coerce': Requires a Node, NodeSet or String argument, and cannot accept a NilClass. (ArgumentError)
(You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node.rb:246:in `children='
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node.rb:234:in `inner_html='
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/polytexnic-1.4.1/lib/polytexnic/utils.rb:170:in `block in highlight_source_code'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:190:in `block in each'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `upto'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `each'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/polytexnic-1.4.1/lib/polytexnic/utils.rb:166:in `highlight_source_code'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/polytexnic-1.4.1/lib/polytexnic/postprocessors/html.rb:1295:in `convert_to_html'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/polytexnic-1.4.1/lib/polytexnic/postprocessors/html.rb:61:in `xml_to_html'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/polytexnic-1.4.1/lib/polytexnic/postprocessor.rb:16:in `postprocess'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/polytexnic-1.4.1/lib/polytexnic.rb:91:in `to_html'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/builders/html.rb:123:in `converted_html'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/builders/html.rb:43:in `build'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/commands/server.rb:47:in `rebuild'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/commands/server.rb:63:in `run'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/softcover-1.5.1/lib/softcover/cli.rb:107:in `server'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/gems/softcover-1.5.1/bin/sc:4:in `<top (required)>'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/bin/sc:23:in `load'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/bin/sc:23:in `<main>'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/bin/ruby_executable_hooks:15:in `eval'
	from /home/james/.rvm/gems/ruby-2.2.2-use-rvm@softcover/bin/ruby_executable_hooks:15:in `<main>'
james@raspberrypi:~/Projects/entr4701_book $ 
```

**Comment by mhartl** [comment]
Just to confirm, you're trying to build a copy of default document created by `softcover new`? If not, that could be the source of your problems. If so, I'm afraid I'm out of ideas.

**Comment by cavalryjim** [comment]
Yes, I tried building using ```softcover new``` and using an existing book.  Same error occurs each time.  Guess it isn't going to work with Raspbian.  Thanks for your help and thanks for putting together this platform.

**Comment by mhartl** [comment]
We'll get things working on Raspberry Pi someday I hope. In the meantime, thank you for your patience.
